### ISSUE TITLE
Abstracting functions

### ISSUE THREAD

**Issue by dliviya** [DSCI-310/DSCI-310-Group-2#2]
Does anyone have any ideas for what functions to abstract? I was thinking we could make a function replaces all the "?" missing data with NA and then removes those lines to make clean data

**Comment by rpeng35** [comment]
Oh I think that's a great idea. 
We can also make a function that makes all box plots for variable vs diagnosis ?

**Comment by eahn01** [comment]
I agree we can also abstract the part where we change all the diagnosis value from 1 to 4 to 1

**Comment by nikizamani** [comment]
hey guys, I agree with those, as the third abstraction, how about adding a Knn results function with the recipe and knn spec input and knn fit with same inputs?

**Comment by rpeng35** [comment]
https://github.com/UBC-DSCI/dsci-310-student/blob/main/practice/test_worksheet_functions_in_r.r
examples for writing tests

**Comment by dliviya** [comment]
Hey guys! I think these are really good ideas, why don't we each make the function that we suggested and create a branch for each of these

**Comment by nikizamani** [comment]
Hey guys, could you review the documentation I wrote for the box plots function? Cheers!

**Comment by dliviya** [comment]
@nikizamani  the documentation looks great! just make sure that there is no space between the function function and the brackets!

**Comment by nikizamani** [comment]
@dliviya Thanks for the note! I'll make sure of that!
