### ISSUE TITLE
Could not reproducibly run the analysis because a package was missing from the provided computational environment. -5

### ISSUE THREAD

**Issue by dliviya** [DSCI-310/DSCI-310-Group-2#9]

**Comment by nikizamani** [comment]
Yeah, that may be the case but I can see the packages. I can see and use the docker on my local computer. However, I can't see the environment in the docker hub. Maybe that's the reason?

**Comment by dliviya** [comment]
that could be it, this is really confusing though :/

**Comment by dliviya** [comment]
PR: https://github.com/DSCI-310/DSCI-310-Group-2/commit/ffad7c9da1a1ee88f96f456065abca002822a6b2
