### ISSUE TITLE
This document should not actually be named `analysis.ipynb`, but have a more descriptive title, related to the project title. -1

### ISSUE THREAD

**Issue by nikizamani** [DSCI-310/DSCI-310-Group-2#94]

**Comment by nikizamani** [comment]
We changed the name of the file to [predicting_heart_disease.ipynb]: 

(https://github.com/DSCI-310/DSCI-310-Group-2/blob/main/src/predicting_heart_disease.ipynb)

**Comment by dliviya** [comment]
good comment
