### ISSUE TITLE
GitHub issue milestones were not used. -5

### ISSUE THREAD

**Issue by dliviya** [DSCI-310/DSCI-310-Group-2#99]

**Comment by dliviya** [comment]
![Uploading Screen Shot 2022-04-05 at 16.54.50.png…]()

**Comment by nikizamani** [comment]
the screenshot does not work

**Comment by nikizamani** [comment]
Here is the link to our issue milestones: 

https://github.com/DSCI-310/DSCI-310-Group-2/milestones
